version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
  app:
    image: myspringbootapp:latest
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/jpa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Zp3pbrya
    ports:
      - "8080:8080"
    depends_on:
      - db
